### PR TITLE
Add workflows to build, sign and release APK

### PR DESCRIPTION
**Pull request by amberin**
The unusual thing here is the workflow for creating a JKS keystore as a repo secret.

The idea is to use Github Actions to generate the key pair used for signing the APKs, and store the resulting key store and its password as secrets in the repository, available for use by the "build and release" actions.

This way, no one contributor needs to be entrusted with key generation, minimizing the opportunities for any one person to keep their own copy of the app signing key.

The only way to read repository secrets is to create and run an Action/workflow where the secrets are printed in an roundabout manner (because Github tries hard to ensure that they are always masked). This can of course be done by repo/organization admins, but it is hard to do without leaving any traces.

In order to be allowed to create repository secrets from a workflow, a fine-grained personal access token is required when running the "Create APK signing secrets" workflow (here given the name SECRETS_CREATION_TOKEN). Since this workflow is only really intended to be run once, and then disabled (but kept as documentation), I recommend creating a very short-lived personal access token for use with this workflow. It should not matter who it belongs to (but it obviously needs to be a repo/org admin).

If anyone else wants to trigger the workflow to overwrite the app signing keys, they must have repo/org admin privileges, so that they can first create a personal access token with permission to write secrets.

### CODE REVIEW

**Review by Emiller88 — APPROVED** [review]
Awesome! Have you found any examples of how other repos are doing this for reference?

**Comment by amberin** [comment]
> Awesome! Have you found any examples of how other repos are doing this for reference?

No, but I have been wondering the same thing. The secret creation thing was fun to do, but I'd feel much better knowing that/if someone else has done similiar things. I didn't know what to search for, but it would probably be wise to look around.

**Comment by amberin** [comment]
I have searched Github for use of the most starred "set repo secret" action repository: hmanzur/actions-set-secret. I looked for projects where the repo secrets updated by this Action actually seem to contain sensitive material. (Most usages seem to be as a persistent storage for dynamic non-sensitive information, such as current version number.)

This project uses Github repo secrets to store a Letsencrypt HTTPS certificate and private key: https://github.com/nhost/cli/blob/7bad17ef9120f02d57d94d86330fa9c7fd3fa90b/.github/workflows/build-cert-weekly.yaml#L27-L53

This project uses repo secrets to store a generated access token for Azure Container Registry: https://github.com/thinktecture-labs/cloud-native-sample/blob/31840135ec3b88a226835b6616f636006d340949/.github/workflows/acrtokenpassword.yml#L13-L30

This is all I have found so far. But there are probably more clever ways to sift through Github.

**Comment by amberin** [comment]
After reading and thinking some more on this and discussing it with colleagues (thanks @mnl), I have reconsidered.

First of all, I have confirmed the following (sorry for the lack of references, but this is hobbled together from many sources):

1) Self-signed certs are still the norm in the Android world. You can create a PKI and chain of trust if you like, but it will not be checked by Android: ["Android currently does not perform CA verification for application certificates."](https://source.android.com/docs/security/features/apksigning)
2) Using a single shared key pair at a time is still the norm. With Play App Signing, sharing a single upload key seems to be the norm.
3) Version 3 of the APK signing scheme, launched in 2018, added a [key rotation feature](https://developer.android.com/tools/apksigner#usage-rotate). This allows a compromised key to be replaced with a new one, although it requires at least two app upgrades by the end user.
4) Play store publishing is a whole different story, as Google signs the final apk ("Play App Signing"). The developer only signs his apk with an "upload key", and Google has a process to replace/renew this key. (I have chosen not to focus on Play store, since we are not there yet.)

I see two problems regarding APK signing with my suggestion in this PR:

a) The secrets are easily lost and cannot be backed up. If they are deleted from Github, or someone overwrites them by accident, a new key must be generated, meaning the next app version will be untrusted by all users. 
b) Not having access to the jks makes key rotation tricky, although probably doable in a pipeline/Action/workflow.

I instead suggest the following:

- Let one maintainer generate the necessary secrets (key pair and keystore password).
- Give each maintainer a copy of the secrets, asking them nicely to store them as securely as possible.
- Upload the secrets as Github repo secrets, and use them for automatic signing of release APKs.
- When the signing certificate is about to expire or a maintainer reports possible key leakage, generate a new key pair. Perform key rotation and publish a new app version signed by both keys, then another app version signed only by the new key. Replace all copies of the previous secrets.

Pros:
- Unlikely that the secrets are permanently lost
- Automated signing in the pipeline makes it easy to release often, with smaller changes.
- Automated signing in the pipeline makes it easier to onboard new contributors/owners.

Cons:
- Github has access to the secrets.
- Secrets need to be shared between code owners, increasing the chances of leakage.

Can anyone see more pros or cons? Or even bigger flaws? Is it acceptable to give the secrets to Github? My gut says yes.

**Comment by amberin** [comment]
The new commits align the branch with my latest comments. I consider this finished and ready for merge.

**Review by colonelpanic8 — APPROVED** [review]

**Pull request merged**
